// export * as AdminApis from "./admin.apis";
export * as AuthApis from "./auth.apis";
export * as UserApis from "./user.apis";
export * as SlotApis from "./slot.apis";
export * as MarketApis from "./market.apis";
export * as ShopApis from "./shop.apis";
export * as NotificationApis from "./notification.apis";
export * as NoticeApis from "./notice.apis";
export * as TicketApis from "./ticket.apis";
export * as PurchaseApis from "./purchase.apis";
export * as CustomerSupportApis from "./customerSupport.apis";
export * as PowerTesterApis from "./powerTester.apis";
export * as ChatbotApis from "./chatbot.apis";
export * as MissionApis from "./mission.apis";
